In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
# Suppress warnings (if desired)
warnings.filterwarnings("ignore")

In [2]:
# Create a dataset with the descriptive features and 10 rows
np.random.seed(0)  # for reproducibility
data = {
    'Age': np.random.randint(20, 70, 10),  # Age values between 20 and 70
    'Income': np.random.randint(20000, 100000, 10),  # Income values between 20,000 and 100,000
    'Spending_Score': np.random.rand(10),  # Random float values between 0 and 1
    'Target': ['Yes' if i > 0.5 else 'No' for i in np.random.rand(10)]
}

df = pd.DataFrame(data)

# Create a Target column with 'Low', 'Medium', 'High' based on Spending_Score
bins = [0, 0.33, 0.66, 1]
labels = ['Low', 'Medium', 'High']
df['Target'] = pd.cut(df['Spending_Score'], bins=bins, labels=labels, include_lowest=True)


df

Age  Income  Spending_Score  Target
0   64   68600        0.832620    High
1   67   59512        0.778157    High
2   20   72620        0.870012    High
3   23   37089        0.978618    High
4   23   52230        0.799159    High
5   59   38983        0.461479  Medium
6   29   26921        0.780529    High
7   39   58804        0.118274     Low
8   41   87699        0.639921  Medium
9   56   90608        0.143353     Low

In [3]:
df['Target'] = df['Target'].map({'Low': 0, 'Medium': 1, 'High': 2})

X = df[['Age', 'Income', 'Spending_Score']]
y = df['Target']



In [4]:
from sklearn.linear_model import LogisticRegression

# Initialize the logistic regression model
clf = LogisticRegression()

# Train the model
clf.fit(X, y)

# Print out the coefficients and intercept
print('Coefficients:', clf.coef_)
print('Intercept:', clf.intercept_)


Coefficients: [[-1.53396263e-02  7.11681749e-06 -3.37749437e-03]
 [ 1.09470914e-02 -1.29032599e-05 -9.21876554e-04]
 [ 4.39253488e-03  5.78644239e-06  4.29937092e-03]]
Intercept: [-0.00132344 -0.00065678  0.00198021]


In [5]:
y_pred = clf.predict(X)

In [6]:
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y, y_pred)
conf_matrix

array([[0, 0, 2],
       [0, 0, 2],
       [0, 0, 6]], dtype=int64)

In [7]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# Compute the metrics
accuracy = accuracy_score(y, y_pred)
f1 = f1_score(y, y_pred, average = 'macro')
precision = precision_score(y, y_pred,  average = 'macro')
recall = recall_score(y, y_pred,  average = 'macro')

# Print the metrics
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")


Accuracy: 0.6000
F1 Score: 0.2500
Precision: 0.2000
Recall: 0.3333
