In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros([10, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.ones([10, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.empty(23)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.29061074e-306,
       1.69119873e-306, 1.78019082e-306, 2.22515195e-307, 4.45040236e-307,
       3.78277835e-307, 4.89533565e-307, 8.34441742e-308, 1.78022342e-306,
       6.23058028e-307, 9.79107872e-307, 6.89807188e-307, 7.56594375e-307,
       6.23060065e-307, 1.78021527e-306, 8.34454050e-308, 1.11261027e-306,
       1.15706896e-306, 1.33512173e-306, 3.49698923e-317])

In [20]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
range(1, 20, 5)

range(1, 20, 5)

In [23]:
list(range(1, 20, 2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [28]:
np.linspace(1, 40, 20)

array([ 1.        ,  3.05263158,  5.10526316,  7.15789474,  9.21052632,
       11.26315789, 13.31578947, 15.36842105, 17.42105263, 19.47368421,
       21.52631579, 23.57894737, 25.63157895, 27.68421053, 29.73684211,
       31.78947368, 33.84210526, 35.89473684, 37.94736842, 40.        ])

In [33]:
np.full([4, 5],100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [35]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])